absoluteurl: https://pearsonca.github.io
baseurl: '/cv'
markdown: kramdown
css:
  active: "active"
exclude:
  - /*.sh
  - README.md
collections:
  pubs:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pubs"
    values:
      layout: "aip"
