absolutedomain: madeforuse.org
localdomain: cv
markdown: kramdown
fullname: Carl A. B. Pearson
shortname: Carl
mailto: blank101@gmail.com
css:
  active: "active"
exclude:
  - '*.sh'
  - README.md
  - CNAME
collections:
  - publication
  - job
  - education
defaults:
  -
    scope:
      path: ""
    values:
      layout: "regular"
